export const MEDDRA_TERMS = [
  { code: 'PT100001', term: 'Hepatitis', soc: 'Hepatobiliary disorders', llt: 'Hepatitis NEC' },
  { code: 'PT100002', term: 'Liver injury', soc: 'Hepatobiliary disorders', llt: 'Liver injury' },
  { code: 'PT100003', term: 'Jaundice', soc: 'Hepatobiliary disorders', llt: 'Jaundice' },
  { code: 'PT100004', term: 'Elevated liver enzymes', soc: 'Hepatobiliary disorders', llt: 'Transaminases increased' },
  { code: 'PT100005', term: 'Cirrhosis', soc: 'Hepatobiliary disorders', llt: 'Cirrhosis' },
  { code: 'PT100006', term: 'Cholestasis', soc: 'Hepatobiliary disorders', llt: 'Cholestasis' },
  { code: 'PT200001', term: 'Rash', soc: 'Skin and subcutaneous tissue disorders', llt: 'Rash NEC' },
  { code: 'PT200002', term: 'Dermatitis', soc: 'Skin and subcutaneous tissue disorders', llt: 'Dermatitis' },
  { code: 'PT200003', term: 'Stevens-Johnson syndrome', soc: 'Skin and subcutaneous tissue disorders', llt: 'Stevens-Johnson syndrome' },
  { code: 'PT200004', term: 'Urticaria', soc: 'Skin and subcutaneous tissue disorders', llt: 'Urticaria' },
  { code: 'PT200005', term: 'Pruritus', soc: 'Skin and subcutaneous tissue disorders', llt: 'Pruritus' },
  { code: 'PT200006', term: 'Alopecia', soc: 'Skin and subcutaneous tissue disorders', llt: 'Alopecia' },
  { code: 'PT300001', term: 'Arthralgia', soc: 'Musculoskeletal and connective tissue disorders', llt: 'Arthralgia' },
  { code: 'PT300002', term: 'Myalgia', soc: 'Musculoskeletal and connective tissue disorders', llt: 'Myalgia' },
  { code: 'PT300003', term: 'Back pain', soc: 'Musculoskeletal and connective tissue disorders', llt: 'Back pain' },
  { code: 'PT300004', term: 'Joint swelling', soc: 'Musculoskeletal and connective tissue disorders', llt: 'Swelling joint' },
  { code: 'PT300005', term: 'Muscle weakness', soc: 'Musculoskeletal and connective tissue disorders', llt: 'Muscle weakness' },
  { code: 'PT400001', term: 'Myocardial infarction', soc: 'Cardiac disorders', llt: 'Myocardial infarction' },
  { code: 'PT400002', term: 'Arrhythmia', soc: 'Cardiac disorders', llt: 'Arrhythmia' },
  { code: 'PT400003', term: 'Heart failure', soc: 'Cardiac disorders', llt: 'Cardiac failure congestive' },
  { code: 'PT400004', term: 'Hypertension', soc: 'Cardiac disorders', llt: 'Hypertension' },
  { code: 'PT400005', term: 'Hypotension', soc: 'Cardiac disorders', llt: 'Hypotension' },
  { code: 'PT400006', term: 'Tachycardia', soc: 'Cardiac disorders', llt: 'Tachycardia' },
  { code: 'PT500001', term: 'Headache', soc: 'Nervous system disorders', llt: 'Headache' },
  { code: 'PT500002', term: 'Dizziness', soc: 'Nervous system disorders', llt: 'Dizziness' },
  { code: 'PT500003', term: 'Seizure', soc: 'Nervous system disorders', llt: 'Seizure' },
  { code: 'PT500004', term: 'Neuropathy', soc: 'Nervous system disorders', llt: 'Neuropathy peripheral' },
  { code: 'PT500005', term: 'Tremor', soc: 'Nervous system disorders', llt: 'Tremor' },
  { code: 'PT500006', term: 'Paresthesia', soc: 'Nervous system disorders', llt: 'Paresthesia' },
  { code: 'PT600001', term: 'Anaphylaxis', soc: 'Immune system disorders', llt: 'Anaphylaxis' },
  { code: 'PT600002', term: 'Angioedema', soc: 'Immune system disorders', llt: 'Angioedema' },
  { code: 'PT600003', term: 'Drug reaction', soc: 'Immune system disorders', llt: 'Drug reaction' },
];

export const DRUGS = [
  { name: 'Aspirin', substance: 'Acetylsalicylic acid', atc: 'N02BA01' },
  { name: 'Ibuprofen', substance: 'Ibuprofen', atc: 'M01AE01' },
  { name: 'Acetaminophen', substance: 'Paracetamol', atc: 'N02BE01' },
  { name: 'Lisinopril', substance: 'Lisinopril', atc: 'C09AA03' },
  { name: 'Metformin', substance: 'Metformin', atc: 'A10BA02' },
  { name: 'Atorvastatin', substance: 'Atorvastatin', atc: 'C10AA05' },
  { name: 'Amoxicillin', substance: 'Amoxicillin', atc: 'J01CA04' },
  { name: 'Ciprofloxacin', substance: 'Ciprofloxacin', atc: 'J01MA02' },
  { name: 'Omeprazole', substance: 'Omeprazole', atc: 'A02BC01' },
  { name: 'Ranitidine', substance: 'Ranitidine', atc: 'A02BA02' },
  { name: 'Sertraline', substance: 'Sertraline', atc: 'N06AB06' },
  { name: 'Paroxetine', substance: 'Paroxetine', atc: 'N06AB05' },
  { name: 'Metoprolol', substance: 'Metoprolol', atc: 'C07AB02' },
  { name: 'Amlodipine', substance: 'Amlodipine', atc: 'C08CA01' },
  { name: 'Warfarin', substance: 'Warfarin', atc: 'B01AA03' },
];

export const WHO_UMC_CAUSALITY = [
  'Certain',
  'Probable',
  'Possible',
  'Unlikely',
  'Unassessable',
  'Unrelated',
];

export const REGULATORY_REQUIREMENTS: Record<string, any> = {
  CDSCO: {
    country: 'India',
    sevenDay: 'Fatal/Life-threatening + Unexpected',
    fifteenDay: 'Serious + Unexpected',
  },
  FDA: {
    country: 'USA',
    sevenDay: 'Fatal/Life-threatening + Unexpected',
    fifteenDay: 'Serious + Unexpected',
  },
  EMA: {
    country: 'Europe',
    sevenDay: 'Fatal/Life-threatening + Unexpected',
    fifteenDay: 'Serious + Unexpected',
  },
};
